[advisories]
ignore = [
        "RUSTSEC-2024-0436", # paste (transitive) is unmaintained because completed
                             # It's fine to ignore it.
]
informational_warnings = ["unmaintained", "unsound"]

[output]
deny = ["warnings", "unsound", "yanked"]
quiet = false