[advisories]
ignore = [
    "RUSTSEC-2024-0388", # Derivative unmaintained -> switch to ark-* 0.5.0 should fix it
]
informational_warnings = ["unmaintained", "unsound"]

[output]
deny = ["warnings", "unsound", "yanked"]
quiet = false